run:
    skip-dirs:
    - samples
    - playground

linters-settings:
    golint:
        min-confidence: 0.9

    gocyclo:
        min-complexity: 15

    revive:
        rules:
        - name: var-naming
          severity: warning
          disabled: true

linters:
    enable:
        - misspell
        - gofmt
        - revive
        - goimports
    disable:
        - errcheck
        - gas
        - megacheck
        - varcheck
    fast: false
