builds:
  -
    binary: nasp
    main: ./cmd/nasp
    goos:
      - linux
    goarch:
      - arm64
      - amd64
    env:
      - CGO_ENABLED=0
    ldflags: -w -s
nfpms:
  -
    package_name: nasp-agent
    description: "NASP CLI and agent service"
    maintainer: Nandor Kracser <nandork@cisco.com>
    license: "MIT"
    formats:
      - deb
      - rpm
    contents:
      - dst: /etc/nasp/config.yaml
        src: config.yaml
      - dst: /etc/nasp/rules/ci.yaml
        src: nasp.d/rules/ci.yaml
      - dst: /etc/nasp/services/ci.yaml
        src: nasp.d/services/ci.yaml
      - dst: /etc/systemd/system/nasp.service
        src: nasp.service
archives:
  - name_template: "{{ .ProjectName }}_agent_{{ .Version }}_{{.Os}}_{{.Arch}}"
checksum:
  name_template: "{{ .ProjectName }}_agent_{{ .Version }}_checksums.txt"
release:
  extra_files:
    - glob: ./nasp_{{ .Version }}_all.deb
