builds:
  -
    binary: camblet
    main: ./cmd/camblet
    goos:
      - linux
    goarch:
      - arm64
      - amd64
    env:
      - CGO_ENABLED=0
    ldflags: -w -s
nfpms:
  -
    package_name: camblet-agent
    description: "Camblet CLI and agent service"
    maintainer: Camblet maintainers <team@camblet.io>
    license: "MIT"
    formats:
      - deb
      - rpm
    contents:
      - dst: /etc/camblet/config.yaml
        src: config.yaml
      - dst: /etc/camblet/rules/sample.yaml
        src: camblet.d/rules/sample.yaml
      - dst: /etc/camblet/services/sample.yaml
        src: camblet.d/services/sample.yaml
      - dst: /etc/systemd/system/nacambletsp.service
        src: deploy/camblet.service
      - dst: /usr/share/doc/camblet/LICENSE
        src: LICENSE
      - dst: /usr/share/doc/camblet/NOTICE
        src: NOTICE
archives:
  - name_template: "{{ .ProjectName }}_agent_{{ .Version }}_{{.Os}}_{{.Arch}}"
checksum:
  name_template: "{{ .ProjectName }}_agent_{{ .Version }}_checksums.txt"
release:
  extra_files:
    - glob: ./camblet{{ .Version }}_all.deb
    - glob: deploy/rpmbuild/noarch/camblet-{{ .Version }}-1.noarch.rpm
