builds:
  -
    binary: nasp
    main: ./cmd/nasp
    goos:
      - linux
    goarch:
      - arm64
      - amd64
nfpms:
  -
    package_name: nasp-agent
    description: "NASP CLI and agent service"
    maintainer: Nandor Kracser <nandork@cisco.com>
    license: "MIT"
    formats:
      - deb
      - rpm
    contents:
      - dst: /etc/nasp/rules/ci.yaml
        src: nasp.d/rules/ci.yaml
      - dst: /etc/nasp/services/ci.yaml
        src: nasp.d/services/ci.yaml
      - dst: /etc/systemd/system/nasp.service
        src: nasp.service
