builds:
  -
    binary: nasp
    main: ./cmd/nasp
    goos:
      - linux
    goarch:
      - arm64
      - amd64
    env:
      - CGO_ENABLED=0
    ldflags: -w -s
nfpms:
  -
    package_name: nasp-agent
    description: "NASP CLI and agent service"
    maintainer: Nasp maintainers <team@nasp.io>
    license: "MIT"
    formats:
      - deb
      - rpm
    contents:
      - dst: /etc/nasp/config.yaml
        src: config.yaml
      - dst: /etc/nasp/rules/sample.yaml
        src: nasp.d/rules/sample.yaml
      - dst: /etc/nasp/services/sample.yaml
        src: nasp.d/services/sample.yaml
      - dst: /etc/systemd/system/nasp.service
        src: deploy/nasp.service
      - dst: /usr/share/doc/nasp/LICENSE
        src: LICENSE
      - dst: /usr/share/doc/nasp/NOTICE
        src: NOTICE
archives:
  - name_template: "{{ .ProjectName }}_agent_{{ .Version }}_{{.Os}}_{{.Arch}}"
checksum:
  name_template: "{{ .ProjectName }}_agent_{{ .Version }}_checksums.txt"
release:
  extra_files:
    - glob: ./nasp_{{ .Version }}_all.deb
    - glob: deploy/rpmbuild/noarch/nasp-{{ .Version }}-1.noarch.rpm
