title: nasp-apt-repo
email: balintmolnar91@gmail.com
description: >- 
  This project is ment to be an aptrepo hosted by github pages
baseurl: ""
url: "https://cisco-open.github.io/nasp"
github_username: baluchicken

# Build settings
theme: minima
plugins:
  - jekyll-feed
exclude:
  - tools/
  - doc/