[package]
name = "webassembly"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "*"
dns-message-parser = "~0.6.0"

[[bin]]
name = "webassembly"
path = "main.rs"


# [lib]
# crate-type = ["cdylib"]
# bench = false
# name = "webassembly"
# path = "main.rs"
