name: Release and deploy DEB/RPM repo

on:
  push:
    tags:
      - "*"

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        name: Checkout nasp
        with:
          fetch-depth: 0

      - name: Build meta package Debian release
        run: |
          sudo apt install -y equivs
          make deb

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.21"

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}